# Site settings
title: Historia
description: My best and worst
baseurl: "/mybestandworst"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
collections:
  pages:
    output: true
    permalink: /:name
  work:
    output: true
    permalink: /:name
emptyArray: []
#  prototype:
#    output: true#
#    permalink: /:name
